### ISSUE TITLE
addIntent is not working...Only addOnLaunchIntent is working.

### ISSUE THREAD

**Issue by ChiragDhangar07** [HKOLWD/AlexaForce#3]
When we just use skill then LaunchIntent get executed.
But when we use skill with Intent then nothing is happening.

**Comment by HKOLWD** [comment]
Have you checked the request log? Do you see an IntentRequest there?

**Comment by ChiragDhangar07** [comment]
HI

I thought it work like.We need to define skills,intent,slot  and utterence
in APEX(salesforce) only.
But it was not working like that.I defined everything in Skill(Alexa).Now
it was working.

Thank
Chirag Dhangar

**Comment by HKOLWD** [comment]
Good to hear you solved it!
