### ISSUE TITLE
Issue while implementing dialogue delegate in alexa

### ISSUE THREAD

**Issue by ChiragDhangar07** [HKOLWD/AlexaForce#4]
Hi ,

When we enables slot filling in amazon alexa skill.We are not getting any response from alexa.
but when we disable slot filling then alexa gave response.

We want to implement dialogue delegate so we are enabling slot filling option in alexa and copied the sample dialog delegate class.

Could you please help regarding this ?

Thanks
Chirag Dhangar

**Comment by HKOLWD** [comment]
Can you post your code?

**Comment by ChiragDhangar07** [comment]
[DemoDialog apex class.txt](https://github.com/HKOLWD/AlexaForce/files/2025259/DemoDialog.apex.class.txt)
[demoDialogHelper class.txt](https://github.com/HKOLWD/AlexaForce/files/2025260/demoDialogHelper.class.txt)
[alexa JSON file.txt](https://github.com/HKOLWD/AlexaForce/files/2025262/alexa.JSON.file.txt)


Only LaunchRequest is working. when i type like below samples then it does not hit salesforce.so no logs are coming.
"the {ServiceTopic} is broken",
                                "the {ServiceTopic} does not work",
                                "the {ServiceTopic} is disconnected",
                                "i have trouble with {ServiceTopic}",
                                "{ServiceTopic}",
                                "please fix {ServiceTopic} ",
                                "fix {ServiceTopic} please",
                                "there's a problem with {ServiceTopic}",
                                "i have a problem with {ServiceTopic}"

**Comment by HKOLWD** [comment]
Please verify the following:
1) When you invoke an Intent does Alexa send an IntentRequest? (you can see this in the JSON of the web interface in the amazon developer portal)
2) If 1) = yes. Do you see the log in Salesforce? You can find the logs in the Request_Log__c tab, each request has a series of Log_Entry__c records. You should be able to see the Alexa JSON in here
3) Try to add your own logs once you get inside your skill, using createLog(title, message). They will be added to the log entries. System.debug won't do much.
